### ISSUE TITLE
 Github tags outdated

### ISSUE THREAD

**Issue by brianpeiris** [leapmotion/leapjs#200]
The version tags in Github have not been updated since 0.6.2 whereas the changelog is at 0.6.4. The version tags are useful for bower installations, please keep them up to date.

**Comment by pehrlich** [comment]
Pushed, sorry about that!

As I tagged 0.6.3 and 0.6.4 together, they appear out of order on the releases page.  Let me know if that's an issue.

https://github.com/leapmotion/leapjs/releases

**Comment by brianpeiris** [comment]
Thanks! Bower is smart enough to order the versions itself, so that's not a problem.
