### ISSUE TITLE
i want to have a beautiful hand in my web app

### ISSUE THREAD

**Issue by nanmenxue** [leapmotion/leapjs#201]
i want to have a hand like https://editor-leapmotion.netdna-ssl.com/leapmotion-examples/javascript/33bb9af093dab3c51c37279e7f68374b5bc87e57/v2/pinch-strength/index.html.livegit
in my web. but i dont know how to code one.there is just example of bones of hand in leap example.please help.if you have a example.

**Comment by pehrlich** [comment]
Have a look: https://github.com/leapmotion/leapjs-rigged-hand

**Comment by nanmenxue** [comment]
thank you~

**Comment by nanmenxue** [comment]
thank you so much ~ i love you ,it is good enough .but i have a little question.the one you give me is a little flat.how to draw a more beautiful hand like the one i give.is it use some tools?or is it just coded by three.js?
