### ISSUE TITLE
Streaming state mismatch 

### ISSUE THREAD

**Issue by dottyz** [leapmotion/leapjs#210]
After device is disconnected then reconnected, the events fired are as followed:

_deviceAttached
deviceStreaming
streamingStarted_

and then after few frame loops the following events are fired:

_deviceStopped
streamingStopped_

even though the device is still connected, and still picks up gestures and streaming new frames with unique ids. 

Here is a short example: http://jsfiddle.net/d5vpydfo/6/

**Comment by codemercenary** [comment]
Bug is trackable to the service in this case.  We've got a fix laid in, it will make it in the next release.
