### ISSUE TITLE
LeapJS does not work in HTTPS page

### ISSUE THREAD

**Issue by sumeetkpatel** [leapmotion/leapjs#217]
Testing the dumper HTTPS, LeapJS doesn't work for me, I think it's falling back to non secure after the secure connection is cancelled?

Works:
http://leapmotion.github.io/leapjs/examples/dumper.html

Does not work:
https://leapmotion.github.io/leapjs/examples/dumper.html

> WebSocket connection to 'wss://127.0.0.1:6436/v6.json' failed: WebSocket opening handshake was canceled
> Mixed Content: The page at 'https://leapmotion.github.io/leapjs/examples/dumper.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://127.0.0.1:6437/v6.json'. 
> This request has been blocked; this endpoint must be available over WSS.
> Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

I am using LeapJS 0.6.4 on Chrome and Run-time: 2.3.1+31549 on Windows

**Comment by pehrlich** [comment]
Hm.  To troubleshoot your connection, try loading over `https`.  No content will load, but chrome will give you the opportunity to view the certificate: 

https://127.0.0.1:6436/v6.json

![screenshot 2016-06-06 11 12 21](https://cloud.githubusercontent.com/assets/407497/15832586/b6dcbb2a-2bd7-11e6-9845-0d7f0cfaa9de.png)

Click details to get:
![screenshot 2016-06-06 11 12 29](https://cloud.githubusercontent.com/assets/407497/15832590/bcc03d28-2bd7-11e6-9c45-d99ae33f6afe.png)


You can also try looking in your Registry for a certificate from Leap Motion:

(this is on mac, but the registration details should look the same):
![screenshot 2016-06-06 11 14 37](https://cloud.githubusercontent.com/assets/407497/15832624/de9610bc-2bd7-11e6-9416-2c76e8254994.png)

The registration gets added during installation, so it is possible that a reinstall could fix a missing cert.

**Comment by sumeetkpatel** [comment]
Yes, awesome.

Going to that address had an invalid certificate
`There are issues with the site's certificate chain (net::ERR_CERT_DATE_INVALID).`

I accepted the certificate anyway and things worked.
I had only just updated my run-time before posting originally, I guess it didn't refresh the certificate.
