### ISSUE TITLE
Vulnerabilities in Outdated Dependencies

### ISSUE THREAD

**Issue by roryhardy** [leapmotion/leapjs#228]
Running `npm audit` shows a few dependencies of leapjs as problematic.

![screen shot 2018-06-01 at 5 22 53 pm](https://user-images.githubusercontent.com/1232730/40868371-0d076d0e-65c1-11e8-891d-446e0c42b700.png)

**Comment by RecursiveCptHook** [comment]
Fixed by https://github.com/leapmotion/leapjs/pull/236, https://github.com/leapmotion/leapjs/pull/237
