### ISSUE TITLE
No leapjs frame events raised in Chrome when not visible

### ISSUE THREAD

**Issue by andrewfstratton** [leapmotion/leapjs#255]
Using the controller.on('frame', handler) handler is not called back when the chrome browser window is hidden, i.e. can be open, but not in view.

Note that the page I am using is still running javascript correctly in the background, and handles other events, such as socket.io, time based, events, etc.  But no leapjs events are raised, until the window is visible again (whether in focus or not).

An easy way to replicate this is to minimize the browser window while the debugger is running with a breakpoint in 'handler' above.  After a few remaining frames, the handler stops being called.

**Comment by zalo** [comment]
This can be changed by passing in the `background` option into the controller's constructor; something like:
```javascript
this.controller = new window.Leap.Controller({ optimizeHMD: false, background: true }).connect();
```
