### ISSUE TITLE
WebSocket connection to 'ws://127.0.0.1:6437/v6.json' failed: leap-1.1.0.min.js:9

### ISSUE THREAD

**Issue by BInyLU** [leapmotion/leapjs#264]
What should I do

**Comment by jselstad** [comment]
Gen2 Leap Motion services do not provide LeapJS support at this time.

Older Tracking Software Releases should still connect after Websockets are enabled in the Control Panel:
https://developer.leapmotion.com/releases/windows-gemini-5-0-0
